name = "bookmarker"
account_id = "805cfd16784a171042a2d06b47886d50"

#main = "./.svelte-kit/cloudflare/_worker.js"
#site.bucket = "./.svelte-kit/cloudflare/"
main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "pnpm run build"

compatibility_date = "2023-06-28"
workers_dev = true

kv_namespaces = [
  { binding = "Bookmarks", id = "0eda854e0e134e338a750b9066c1e2a2", preview_id="8e8298534f0143ecbe35d9d90777bcad" },
  { binding = "Users", id = "5ce37404bd864e3e8eb1ae2208aa0aa2", preview_id="fd6bcc3bf5694316bfe0832a716238f9" },
]
